// Developer note: Do not edit this file directly unless necessary.

export type Role = 'CLIENT' | 'LAWYER' | 'COURT_ADMIN' | 'ADMIN' | 'ORGANIZATION';

export interface User {
  id: string;
  name: string;
  email: string;
  phone: number;
  role: Role;
  avatar?: string;
  /** Present when role === 'ORGANIZATION' (decoded from JWT). */
  organizationId?: string | null;
  /**
   * Server-side flag set when an admin invites a user with a temporary
   * password (or after a forced reset). Frontend route guard bounces such
   * users to `/auth/change-password` until they rotate their password.
   * Cleared by `authApi.changePassword` on success.
   */
  mustChangePassword?: boolean;
}

// ── Organization (Law Firm) ────────────────────────────────────────────

export type OrgAppointmentRequestStatus =
  | 'PENDING'
  | 'ASSIGNED'
  | 'REJECTED'
  | 'CANCELLED'
  | 'EXPIRED'

export interface Organization {
  id: string
  name: string
  email: string
  phone: string
  avatarUrl?: string | null
  isVerified: boolean
  emailVerified: boolean
  registrationNumber?: string | null
  registrationCertUrl?: string | null
  gstNumber?: string | null
  gstProofUrl?: string | null
  panNumber?: string | null
  about?: string | null
  website?: string | null
  practiceAreas: string[]
  /** PAISE — divide by 100 for display. */
  consultationFee?: number | null
  country?: string
  state?: string
  district?: string
  city?: string
  pincode?: string
  address?: string
  latitude?: number | null
  longitude?: number | null
  createdAt: string
  updatedAt: string
}

export interface VerifiedLawyer {
  id: string
  name: string
  email?: string
  phone?: string
  avatarUrl?: string | null
  licenseNumber?: string | null
  barCouncilId?: string | null
  specializations?: string[]
  feePerConsultation?: number | null
  pincode?: string | null
  city?: string | null
  state?: string | null
  bio?: string | null
  experienceYears?: number | null
  isVerified?: boolean
}

export interface OrgAppointmentRequest {
  id: string
  organizationId: string
  clientId: string
  scheduledAt: string
  durationMins: number
  meetingType: 'AUDIO_CALL' | 'VIDEO_CALL' | 'OFFICE_VISIT' | null
  notes?: string | null
  status: OrgAppointmentRequestStatus
  rejectionReason?: string | null
  assignedLawyerId?: string | null
  appointmentId?: string | null
  organization: {
    id: string
    name: string
    avatarUrl?: string | null
    consultationFee?: number | null
    pincode?: string | null
    city?: string | null
    state?: string | null
  }
  client: {
    id: string
    name: string
    email: string
    phone: string
    avatarUrl?: string | null
  }
  assignedLawyer?: {
    id: string
    name: string
    email: string
    avatarUrl?: string | null
  } | null
  appointment?: {
    id: string
    status: string
    scheduledAt: string
    paymentId?: string | null
  } | null
  /**
   * Pre-paid booking payment. Populated for org-appointment requests created
   * via the new pay-at-booking flow — the FE uses `providerOrderId` to
   * re-open Razorpay checkout if the user closed it mid-flow without paying.
   * `amount` is in rupees (the server normalises before returning).
   */
  payment?: {
    id: string
    providerOrderId: string | null
    amount: number
    currency: string
    status: 'PENDING' | 'COMPLETED' | 'FAILED' | 'REFUNDED' | string
    provider?: string | null
  } | null
  createdAt: string
  updatedAt: string
}

export interface OrgVerificationRequest {
  id: string
  organizationId: string
  courtAdminId: string
  status: 'PENDING' | 'APPROVED' | 'REJECTED'
  remarks?: string | null
  verifiedAt?: string | null
  createdAt: string
  organization: Organization
}

export interface Lawyer {
  id: string;
  name: string;
  specialization: string[];
  experienceYears: number;
  rating: number;
  fee: number;
  location: string;
  languages: string[];
  avatar?: string;
  isVerified?: boolean;
  reviewsCount?: number;
  distance?: number; // km — only present in geo search
}

export interface Appointment {
  id: string;
  lawyerId: string;
  clientId: string;
  datetime: string;
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled' | 'rejected';
  paymentId?: string;
}

export interface Case {
  id: string;
  title: string;
  clientId: string;
  lawyerId: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface Document {
  id: string;
  caseId: string;
  name: string;
  url: string;
  uploadedBy: string;
  uploadedAt: string;
  type: string;
}

export interface ChatMessage {
  id: string;
  chatId: string;
  senderId: string;
  text: string;
  attachments?: string[];
  createdAt: string;
  readAt?: string;
}

export interface TimelineEvent {
  id: string;
  title: string;
  date: string;
  description?: string;
  type: 'hearing' | 'task' | 'document';
}

export interface AgreementTemplate {
  id: string
  lawyerId: string
  title: string
  description?: string
  content: string
  category?: string
  isDefault: boolean
  createdAt: string
  updatedAt: string
}

export type TransactionType = 'CREDIT' | 'DEBIT' | 'WITHDRAWAL' | 'REFUND' | 'PAYMENT' | 'TRANSFER'
export type TransactionStatus = 'COMPLETED' | 'FAILED'

export interface WalletTransaction {
  id: string
  walletId: string
  userId: string
  amount: number
  type: TransactionType
  status: TransactionStatus
  description: string
  referenceId?: string | null
  counterpartyId?: string | null
  bankAccountId?: string | null
  createdAt: string
}

// ── Push Notifications ───────────────────────────────────────────────

// Mirrors the backend `enum NotificationType` in
// lawsuit-server/prisma/schema.prisma. Keep in sync when the backend changes —
// NotificationModal.resolveRoute() maps each of these to a destination.
export type NotificationType =
  | 'APPOINTMENT_BOOKED'
  | 'APPOINTMENT_CONFIRMED'
  | 'APPOINTMENT_CANCELLED'
  | 'APPOINTMENT_REMINDER'
  | 'APPOINTMENT_RESCHEDULED'
  | 'NEW_MESSAGE'
  | 'TASK_ASSIGNED'
  | 'DOCUMENT_UPLOADED'
  | 'CASE_UPDATE'
  | 'PAYMENT_RECEIVED'
  | 'WALLET_CREDIT'
  | 'WALLET_DEBIT'
  | 'REVIEW_RECEIVED'
  | 'VIDEO_CALL'
  | 'CONSULTATION_COMPLETED'
  // Mediation — legacy standalone flow
  | 'MEDIATION_INVITE'
  | 'MEDIATION_ACCEPTED'
  | 'MEDIATION_DECLINED'
  | 'MEDIATION_MEDIATOR_SELECTED'
  | 'MEDIATION_SESSION_READY'
  | 'MEDIATION_RESOLVED'
  | 'MEDIATION_ESCALATED'
  // Mediation — canonical Mediation Act 2023 flow
  | 'MEDIATION_INITIATED'
  | 'MEDIATION_INVITED'
  | 'MEDIATION_INVITE_EXPIRED'
  | 'MEDIATION_LAWYER_NEEDED'
  | 'MEDIATION_MEDIATOR_PROPOSED'
  | 'MEDIATION_MEDIATOR_PICKED'
  | 'MEDIATION_ACTIVE'
  | 'MEDIATION_SETTLEMENT_DRAFT'
  | 'MEDIATION_SETTLED'
  | 'MEDIATION_NON_SETTLEMENT'
  | 'MEDIATION_WITHDRAWN'
  | 'MEDIATION_WARNING_14D'
  | 'MEDIATION_EXPIRED'
  // Organization (law-firm) flow
  | 'ORGANIZATION_VERIFIED'
  | 'ORGANIZATION_REJECTED'
  | 'ORG_APPOINTMENT_REQUEST_RECEIVED'
  | 'ORG_APPOINTMENT_REQUEST_ASSIGNED'
  | 'ORG_APPOINTMENT_REQUEST_REJECTED'
  // Court admin authorization
  | 'COURT_ADMIN_AUTHORIZATION_PENDING'
  | 'COURT_ADMIN_AUTHORIZED'
  | 'COURT_ADMIN_REJECTED'
  | 'ANNOUNCEMENT'

export interface NotificationData {
  appointmentId?: string
  chatId?: string
  caseId?: string
  referenceId?: string
  // Mediation flow (mediationId → detail page; token → public invite-accept page)
  mediationId?: string
  token?: string
  // Organization-flow extras
  requestId?: string
  paymentId?: string
  organizationId?: string
  lawyerId?: string
}

export interface Notification {
  id: string
  userId?: string
  title: string
  body: string
  type: NotificationType
  data: NotificationData
  isRead: boolean
  readAt?: string | null
  createdAt: string
}

export interface NotificationListResponse {
  items: Notification[]
  total: number
  unreadCount: number
  page: number
  limit: number
}