// Developer note: Do not edit this file directly unless necessary.

export interface User {
  id: string;
  name: string;
  email: string;
  phone: number;
  role: 'CLIENT' | 'LAWYER' | 'ADMIN' | 'COURT_ADMIN';
  avatar?: string;
}

export interface Lawyer {
  id: string;
  name: string;
  specialization: string[];
  experienceYears: number;
  rating: number;
  fee: number;
  location: string;
  languages: string[];
  avatar?: string;
  isVerified?: boolean;
  reviewsCount?: number;
  distance?: number; // km — only present in geo search
}

export interface Appointment {
  id: string;
  lawyerId: string;
  clientId: string;
  datetime: string;
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled' | 'rejected';
  paymentId?: string;
}

export interface Case {
  id: string;
  title: string;
  clientId: string;
  lawyerId: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface Document {
  id: string;
  caseId: string;
  name: string;
  url: string;
  uploadedBy: string;
  uploadedAt: string;
  type: string;
}

export interface ChatMessage {
  id: string;
  chatId: string;
  senderId: string;
  text: string;
  attachments?: string[];
  createdAt: string;
  readAt?: string;
}

export interface TimelineEvent {
  id: string;
  title: string;
  date: string;
  description?: string;
  type: 'hearing' | 'task' | 'document';
}

export interface AgreementTemplate {
  id: string
  lawyerId: string
  title: string
  description?: string
  content: string
  category?: string
  isDefault: boolean
  createdAt: string
  updatedAt: string
}

export type TransactionType = 'CREDIT' | 'DEBIT' | 'WITHDRAWAL' | 'REFUND' | 'PAYMENT' | 'TRANSFER'
export type TransactionStatus = 'COMPLETED' | 'FAILED'

export interface WalletTransaction {
  id: string
  walletId: string
  userId: string
  amount: number
  type: TransactionType
  status: TransactionStatus
  description: string
  referenceId?: string | null
  counterpartyId?: string | null
  bankAccountId?: string | null
  createdAt: string
}

// ── Push Notifications ───────────────────────────────────────────────

export type NotificationType =
  | 'APPOINTMENT_BOOKED'
  | 'APPOINTMENT_CONFIRMED'
  | 'APPOINTMENT_CANCELLED'
  | 'APPOINTMENT_REMINDER'
  | 'APPOINTMENT_RESCHEDULED'
  | 'NEW_MESSAGE'
  | 'PAYMENT_RECEIVED'
  | 'WALLET_CREDIT'
  | 'WALLET_DEBIT'
  | 'CONSULTATION_COMPLETED'
  | 'REVIEW_RECEIVED'
  | 'CASE_UPDATE'
  | 'DOCUMENT_UPLOADED'
  | 'VIDEO_CALL'
  | 'TASK_ASSIGNED'

export interface NotificationData {
  appointmentId?: string
  chatId?: string
  caseId?: string
  referenceId?: string
  link?: string
}

export interface Notification {
  id: string
  userId?: string
  title: string
  body: string
  type: NotificationType
  data: NotificationData
  isRead: boolean
  readAt?: string | null
  createdAt: string
}

export interface NotificationListResponse {
  items: Notification[]
  total: number
  unreadCount: number
  page: number
  limit: number
}