// Developer note: Do not edit this file directly unless necessary.

import { create } from 'zustand'
import storage from '@/utils/storage'
import { authApi } from '@/services/api'
import type { User } from '@/types'

/**
 * Decode a JWT payload (no verification — just for reading claims like organizationId).
 * Returns null on any parse error.
 */
function decodeJwt<T = Record<string, any>>(token: string | null | undefined): T | null {
  if (!token) return null
  try {
    const parts = token.split('.')
    if (parts.length !== 3) return null
    const payload = parts[1]
    // Base64URL decode
    const base64 = payload.replace(/-/g, '+').replace(/_/g, '/')
    const padded = base64 + '='.repeat((4 - (base64.length % 4)) % 4)
    const json = atob(padded)
    return JSON.parse(json) as T
  } catch {
    return null
  }
}

/** Merge JWT claims into the user object (organizationId, role override). */
function mergeJwtClaims(user: any, token: string | null | undefined): any {
  const claims = decodeJwt<{ organizationId?: string | null; role?: string }>(token)
  if (!claims) return user
  return {
    ...user,
    ...(claims.organizationId !== undefined ? { organizationId: claims.organizationId } : {}),
  }
}

interface AuthState {
  user: User | null
  token: string | null
  isLoading: boolean
  isAuthenticated: boolean
  error: string | null
  login: (email: string, password: string) => Promise<void>
  register: (data: { name: string; email: string; password: string; role: string; phone?: number | string; registrationNumber?: string; pincode?: string; courtDetails?: any }) => Promise<void>
  verifyOtp: (identifier: string, code: string) => Promise<void>
  requestOtp: (identifier: string) => Promise<any>
  logout: () => void
  clearError: () => void
}

export const useAuthStore = create<AuthState>((set) => ({
  user: storage.getUserData(),
  token: storage.getAuthToken(),
  isLoading: false,
  isAuthenticated: !!storage.getAuthToken(),
  error: null,

  login: async (email: string, password: string) => {
    set({ isLoading: true, error: null })
    try {
      const response = await authApi.login(email, password)
      // backend returns { user, accessToken, refreshToken }
      const { user, accessToken, refreshToken } = response.data
      // Merge organizationId (and any other JWT claims) onto the user object
      const enrichedUser = mergeJwtClaims(user, accessToken)
      storage.setUserData(enrichedUser)
      if (accessToken) storage.setAuthToken(accessToken)
      if (refreshToken) storage.setRefreshToken(refreshToken)
      set({ user: enrichedUser, token: accessToken ?? null, isAuthenticated: !!accessToken })
    } catch (error: any) {
      set({ error: error.response?.data?.message || 'Login failed' })
      throw error
    } finally {
      set({ isLoading: false })
    }
  },

  register: async (data) => {
    set({ isLoading: true, error: null })
    try {
      // Ensure phone is a string when calling backend and role is uppercase to match backend enums
      const payload = {
        ...data,
        phone: data.phone ? String(data.phone) : undefined,
        role: (data.role || '').toString().toUpperCase(),
      }
      const response = await authApi.register(payload as any)
      // backend returns { user, accessToken, refreshToken }
      const { user, accessToken, refreshToken } = response.data
      const enrichedUser = mergeJwtClaims(user, accessToken)
      storage.setUserData(enrichedUser)
      if (accessToken) storage.setAuthToken(accessToken)
      if (refreshToken) storage.setRefreshToken(refreshToken)
      set({ user: enrichedUser, token: accessToken ?? null, isAuthenticated: !!accessToken })
    } catch (error: any) {
      set({ error: error.response?.data?.message || 'Registration failed' })
      throw error
    } finally {
      set({ isLoading: false })
    }
  },

  verifyOtp: async (identifier: string, code: string) => {
    set({ isLoading: true, error: null })
    try {
      const response = await authApi.verifyOtp(identifier, code)
      // backend returns { user, accessToken, refreshToken }
      const { user, accessToken, refreshToken } = response.data
      const enrichedUser = mergeJwtClaims(user, accessToken)
      storage.setUserData(enrichedUser)
      if (accessToken) storage.setAuthToken(accessToken)
      if (refreshToken) storage.setRefreshToken(refreshToken)
      set({ user: enrichedUser, token: accessToken ?? null, isAuthenticated: !!accessToken })
    } catch (error: any) {
      set({ error: error.response?.data?.message || 'OTP verification failed' })
      throw error
    } finally {
      set({ isLoading: false })
    }
  },

  requestOtp: async (identifier: string) => {
    set({ isLoading: true, error: null })
    try {
      const response = await authApi.requestOtp(identifier)
      return response.data
    } catch (error: any) {
      set({ error: error.response?.data?.message || 'OTP request failed' })
      throw error
    } finally {
      set({ isLoading: false })
    }
  },

  logout: () => {
    try {
      const refresh = storage.getRefreshToken()
      if (refresh) {
        // fire-and-forget logout to backend
        authApi.logout(refresh).catch(() => { })
      }
    } catch (err) {
      // ignore
    }
    storage.clear()
    set({ user: null, token: null, isAuthenticated: false })
  },

  clearError: () => set({ error: null }),
}))

export default useAuthStore