// Developer note: Do not edit this file directly unless necessary.

import { create } from 'zustand'
import storage from '@/utils/storage'
import { authApi } from '@/services/api'
import type { User } from '@/types'

interface AuthState {
  user: User | null
  token: string | null
  isLoading: boolean
  isAuthenticated: boolean
  error: string | null
  login: (email: string, password: string) => Promise<void>
  register: (data: { name: string; email: string; password: string; role: string; phone?: number | string }) => Promise<void>
  verifyOtp: (identifier: string, code: string) => Promise<void>
  requestOtp: (identifier: string) => Promise<any>
  logout: () => void
  clearError: () => void
}

export const useAuthStore = create<AuthState>((set) => ({
  user: storage.getUserData(),
  token: storage.getAuthToken(),
  isLoading: false,
  isAuthenticated: !!storage.getAuthToken(),
  error: null,

  login: async (email: string, password: string) => {
    set({ isLoading: true, error: null })
    try {
      const response = await authApi.login(email, password)
      // backend returns { user, accessToken, refreshToken }
      const { user, accessToken, refreshToken } = response.data
      storage.setUserData(user)
      if (accessToken) storage.setAuthToken(accessToken)
      if (refreshToken) storage.setRefreshToken(refreshToken)
      set({ user, token: accessToken ?? null, isAuthenticated: !!accessToken })
    } catch (error: any) {
      set({ error: error.response?.data?.message || 'Login failed' })
      throw error
    } finally {
      set({ isLoading: false })
    }
  },

  register: async (data) => {
    set({ isLoading: true, error: null })
    try {
      // Ensure phone is a string when calling backend and role is uppercase to match backend enums
      const payload = {
        ...data,
        phone: data.phone ? String(data.phone) : undefined,
        role: (data.role || '').toString().toUpperCase(),
      }
      const response = await authApi.register(payload as any)
      // backend returns { user, accessToken, refreshToken }
      const { user, accessToken, refreshToken } = response.data
      storage.setUserData({id:user.id, role:user.role,})
      if (accessToken) storage.setAuthToken(accessToken)
      if (refreshToken) storage.setRefreshToken(refreshToken)
      set({ user, token: accessToken ?? null, isAuthenticated: !!accessToken })
    } catch (error: any) {
      set({ error: error.response?.data?.message || 'Registration failed' })
      throw error
    } finally {
      set({ isLoading: false })
    }
  },

  verifyOtp: async (identifier: string, code: string) => {
    set({ isLoading: true, error: null })
    try {
      const response = await authApi.verifyOtp(identifier, code)
      // backend returns { user, accessToken, refreshToken }
      const { user, accessToken, refreshToken } = response.data
      storage.setUserData(user)
      if (accessToken) storage.setAuthToken(accessToken)
      if (refreshToken) storage.setRefreshToken(refreshToken)
      set({ user, token: accessToken ?? null, isAuthenticated: !!accessToken })
    } catch (error: any) {
      set({ error: error.response?.data?.message || 'OTP verification failed' })
      throw error
    } finally {
      set({ isLoading: false })
    }
  },

  requestOtp: async (identifier: string) => {
    set({ isLoading: true, error: null })
    try {
      const response = await authApi.requestOtp(identifier)
      return response.data
    } catch (error: any) {
      set({ error: error.response?.data?.message || 'OTP request failed' })
      throw error
    } finally {
      set({ isLoading: false })
    }
  },

  logout: () => {
    try {
      const refresh = storage.getRefreshToken()
      if (refresh) {
        // fire-and-forget logout to backend
        authApi.logout(refresh).catch(() => {})
      }
    } catch (err) {
      // ignore
    }
    storage.clear()
    set({ user: null, token: null, isAuthenticated: false })
  },

  clearError: () => set({ error: null }),
}))

export default useAuthStore