// Developer note: Do not edit this file directly unless necessary.

import { create } from 'zustand'
import type { Lawyer } from '@/types'
import { lawyersApi } from '@/services/api'

interface FilterOptions {
  specializations: string[]
  locations: string[]
  languages: string[]
}

interface LawyerStore {
  lawyers: Lawyer[]
  loading: boolean
  error: string | null
  total: number
  page: number
  limit: number
  filterOptions: FilterOptions
  allFilterOptions: FilterOptions
  fetchLawyers: (filters?: { q?: string; specialization?: string; location?: string; maxFee?: number; languages?: string[]; latitude?: number; longitude?: number; radiusKm?: number; state?: string; sortBy?: string; order?: 'asc' | 'desc' }, page?: number, limit?: number) => Promise<void>
  fetchLawyerById: (id: string) => Promise<Lawyer | null>
}

export const useLawyerStore = create<LawyerStore>((set, get) => ({
  lawyers: [],
  loading: false,
  error: null,
  total: 0,
  page: 1,
  limit: 10,
  filterOptions: { specializations: [], locations: [], languages: [] },
  allFilterOptions: { specializations: [], locations: [], languages: [] },

  fetchLawyers: async (filters, page = 1, limit = 10) => {
    set({ loading: true, error: null })
    try {
      // Map our local filter keys to backend query params
      const params: any = {
        page,
        limit,
      }

      if (filters) {
        if (filters.q) params.q = filters.q
        if (filters.specialization) params.specialization = filters.specialization
        if (filters.location) params.city = filters.location
        if (filters.state) params.state = filters.state
        if (filters.maxFee) params.maxFee = filters.maxFee
        if (filters.languages) params.languages = Array.isArray(filters.languages) ? filters.languages.join(',') : filters.languages
        if (filters.latitude != null) params.latitude = filters.latitude
        if (filters.longitude != null) params.longitude = filters.longitude
        if (filters.radiusKm) params.radiusKm = filters.radiusKm
        if (filters.sortBy) params.sortBy = filters.sortBy
        if (filters.order) params.order = filters.order
      }

      const res = await lawyersApi.getAll(params)
      const payload = res.data || {}

      // backend returns { items, total, page, limit, filters }
      const items = payload.items || payload.data || []
      const total = payload.total || 0
      const respPage = payload.page || page
      const respLimit = payload.limit || limit
      const filtersResp = payload.filters || payload.filterOptions || {}

      // Map backend items to our frontend Lawyer type
      const lawyers: Lawyer[] = items.map((it: any) => ({
        id: it.id,
        name: it.user?.name || it.user?.fullName || it.name || it.user?.email || 'Unknown',
        specialization: it.specializations || it.specialization || [],
        experienceYears: it.experienceYears || it.yearsExperience || 0,
        rating: it.rating ?? 0,
        fee: (it.feePerConsultation || it.fee || 0) / 100,
        location: it.city || it.location || '',
        languages: it.languages || [],
        avatar: it.user?.avatar || it.avatarUrl || it.user?.avatarUrl || undefined,
        isVerified: it.isVerified ?? false,
        reviewsCount: it.totalReviews ?? 0,
        distance: it.distance ?? undefined,
      }))

      // If backend didn't provide filterOptions, derive them from returned items
      let specializations: string[] = (filtersResp.specializations || []) as string[]
      let locations: string[] = (filtersResp.locations || []) as string[]
      let languagesArr: string[] = (filtersResp.languages || []) as string[]

      if ((!specializations || specializations.length === 0) && items.length) {
        const specSet = new Set<string>()
        items.forEach((it: any) => (it.specializations || it.specialization || []).forEach((s: string) => specSet.add(s)))
        specializations = Array.from(specSet)
      }

      if ((!locations || locations.length === 0) && items.length) {
        const locSet = new Set<string>()
        items.forEach((it: any) => {
          const loc = it.city || it.location
          if (loc) locSet.add(loc)
        })
        locations = Array.from(locSet)
      }

      if ((!languagesArr || languagesArr.length === 0) && items.length) {
        const langSet = new Set<string>()
        items.forEach((it: any) => (it.languages || []).forEach((l: string) => langSet.add(l)))
        languagesArr = Array.from(langSet)
      }

      // Merge with master list so selecting a filter doesn't remove other options
      const currentAll = get().allFilterOptions || { specializations: [], locations: [], languages: [] }

      const mergedSpecializations = Array.from(new Set([...(currentAll.specializations || []), ...(specializations || [])]))
      const mergedLocations = Array.from(new Set([...(currentAll.locations || []), ...(locations || [])]))
      const mergedLanguages = Array.from(new Set([...(currentAll.languages || []), ...(languagesArr || [])]))

      const updatedAll = {
        specializations: mergedSpecializations,
        locations: mergedLocations,
        languages: mergedLanguages,
      }

      set({ lawyers, total, page: respPage, limit: respLimit, filterOptions: updatedAll, allFilterOptions: updatedAll, loading: false })
    } catch (error) {
      console.error('fetchLawyers error', error)
      set({ error: 'Failed to fetch lawyers', loading: false })
    }
  },

  fetchLawyerById: async (id) => {
    set({ loading: true, error: null })
    try {
      const res = await lawyersApi.getById(id)
      const payload = res.data || {}
      const it = payload.lawyer || payload || res.data
      if (!it) return null

      const lawyer: Lawyer = {
        id: it.id,
        name: it.user?.name || it.user?.fullName || it.name || it.user?.email || 'Unknown',
        specialization: it.specializations || it.specialization || [],
        experienceYears: it.experienceYears || it.yearsExperience || 0,
        rating: it.rating ?? 0,
        fee: (it.feePerConsultation || it.fee || 0) / 100,
        location: it.city || it.location || '',
        languages: it.languages || [],
        avatar: it.user?.avatar || undefined,
      }

      set({ loading: false })
      return lawyer
    } catch (error) {
      console.error('fetchLawyerById error', error)
      set({ error: 'Failed to fetch lawyer details', loading: false })
      return null
    }
  }
}))