// Developer note: Do not edit this file directly unless necessary.

import { format, parse, isValid, addMinutes, addHours, addDays } from 'date-fns'

export const DATE_FORMAT = 'yyyy-MM-dd'
export const TIME_FORMAT = 'HH:mm'
export const DATETIME_FORMAT = `${DATE_FORMAT} ${TIME_FORMAT}`

export const formatDate = (date: Date | string | number): string => {
  const parsedDate = typeof date === 'string' ? new Date(date) : date
  return format(parsedDate, DATE_FORMAT)
}

export const formatTime = (date: Date | string | number): string => {
  const parsedDate = typeof date === 'string' ? new Date(date) : date
  return format(parsedDate, TIME_FORMAT)
}

export const formatDateTime = (date: Date | string | number): string => {
  const parsedDate = typeof date === 'string' ? new Date(date) : date
  return format(parsedDate, DATETIME_FORMAT)
}

export const parseDate = (dateString: string): Date | null => {
  const parsedDate = parse(dateString, DATE_FORMAT, new Date())
  return isValid(parsedDate) ? parsedDate : null
}

export const parseTime = (timeString: string): Date | null => {
  const parsedTime = parse(timeString, TIME_FORMAT, new Date())
  return isValid(parsedTime) ? parsedTime : null
}

export const parseDateTime = (dateTimeString: string): Date | null => {
  const parsedDateTime = parse(dateTimeString, DATETIME_FORMAT, new Date())
  return isValid(parsedDateTime) ? parsedDateTime : null
}

export const addTimeToDate = (date: Date, minutes: number): Date => {
  return addMinutes(date, minutes)
}

export const addHoursToDate = (date: Date, hours: number): Date => {
  return addHours(date, hours)
}

export const addDaysToDate = (date: Date, days: number): Date => {
  return addDays(date, days)
}

export const isValidDate = (date: any): boolean => {
  if (!date) return false
  const parsedDate = new Date(date)
  return isValid(parsedDate)
}

export const isValidTime = (time: string): boolean => {
  if (!time) return false
  const [hours, minutes] = time.split(':').map(Number)
  return (
    !isNaN(hours) &&
    !isNaN(minutes) &&
    hours >= 0 &&
    hours < 24 &&
    minutes >= 0 &&
    minutes < 60
  )
}

export const isValidDateTime = (dateTime: string): boolean => {
  if (!dateTime) return false
  const parsedDateTime = parseDateTime(dateTime)
  return parsedDateTime !== null
}

export const getTimeSlots = (
  startTime: string,
  endTime: string,
  intervalMinutes: number = 30
): string[] => {
  const slots: string[] = []
  const start = parseTime(startTime)
  const end = parseTime(endTime)

  if (!start || !end) return slots

  let current = start
  while (current <= end) {
    slots.push(formatTime(current))
    current = addMinutes(current, intervalMinutes)
  }

  return slots
}

export const getDateRange = (startDate: Date, endDate: Date): Date[] => {
  const dates: Date[] = []
  let currentDate = startDate

  while (currentDate <= endDate) {
    dates.push(new Date(currentDate))
    currentDate = addDays(currentDate, 1)
  }

  return dates
}

export default {
  formatDate,
  formatTime,
  formatDateTime,
  parseDate,
  parseTime,
  parseDateTime,
  addTimeToDate,
  addHoursToDate,
  addDaysToDate,
  isValidDate,
  isValidTime,
  isValidDateTime,
  getTimeSlots,
  getDateRange,
}