// Developer note: Do not edit this file directly unless necessary.

const APP_PREFIX = 'lawsoft_'

export const StorageKeys = {
  AUTH_TOKEN: `${APP_PREFIX}auth_token`,
  REFRESH_TOKEN: `${APP_PREFIX}refresh_token`,
  USER_DATA: `${APP_PREFIX}user_data`,
  LANGUAGE: `${APP_PREFIX}language`,
  THEME: `${APP_PREFIX}theme`,
  REMEMBER_ME: `${APP_PREFIX}remember_me`,
  LAST_ROUTE: `${APP_PREFIX}last_route`,
} as const

class StorageService {
  private static instance: StorageService
  private storage: Storage

  private constructor(useSessionStorage: boolean = false) {
    this.storage = useSessionStorage ? sessionStorage : localStorage
  }

  public static getInstance(useSessionStorage: boolean = false): StorageService {
    if (!StorageService.instance) {
      StorageService.instance = new StorageService(useSessionStorage)
    }
    return StorageService.instance
  }

  setItem(key: string, value: any): void {
    try {
      const serializedValue = JSON.stringify(value)
      this.storage.setItem(key, serializedValue)
    } catch (error) {
      console.error('Error saving to storage:', error)
    }
  }

  getItem<T>(key: string): T | null {
    try {
      const item = this.storage.getItem(key)
      return item ? JSON.parse(item) : null
    } catch (error) {
      console.error('Error reading from storage:', error)
      return null
    }
  }

  removeItem(key: string): void {
    try {
      this.storage.removeItem(key)
    } catch (error) {
      console.error('Error removing from storage:', error)
    }
  }

  clear(): void {
    try {
      // Only clear items with our app prefix
      Object.keys(this.storage).forEach(key => {
        if (key.startsWith(APP_PREFIX)) {
          this.storage.removeItem(key)
        }
      })
    } catch (error) {
      console.error('Error clearing storage:', error)
    }
  }

  // Utility methods for common operations
  setAuthToken(token: string): void {
    this.setItem(StorageKeys.AUTH_TOKEN, token)
  }
  getAuthToken(): string | null {
    return this.getItem(StorageKeys.AUTH_TOKEN)
  }

  setRefreshToken(token: string): void {
    this.setItem(StorageKeys.REFRESH_TOKEN, token)
  }

  getRefreshToken(): string | null {
    return this.getItem(StorageKeys.REFRESH_TOKEN)
  }



  setUserData(userData: any): void {
    this.setItem(StorageKeys.USER_DATA, userData)
  }

  getUserData<T>(): T | null {
    return this.getItem(StorageKeys.USER_DATA)
  }

  setLanguage(language: string): void {
    this.setItem(StorageKeys.LANGUAGE, language)
  }

  getLanguage(): string | null {
    return this.getItem(StorageKeys.LANGUAGE)
  }

  setTheme(theme: string): void {
    this.setItem(StorageKeys.THEME, theme)
  }

  getTheme(): string | null {
    return this.getItem(StorageKeys.THEME)
  }

  setRememberMe(value: boolean): void {
    this.setItem(StorageKeys.REMEMBER_ME, value)
  }

  getRememberMe(): boolean {
    return this.getItem(StorageKeys.REMEMBER_ME) ?? false
  }

  setLastRoute(route: string): void {
    this.setItem(StorageKeys.LAST_ROUTE, route)
  }

  getLastRoute(): string | null {
    return this.getItem(StorageKeys.LAST_ROUTE)
  }
}

export const storage = StorageService.getInstance()
export default storage