// Developer note: Do not edit this file directly unless necessary.

// Email validation
export const isValidEmail = (email: string): boolean => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  return emailRegex.test(email)
}

// Password validation
// Requires minimum 8 characters, at least one uppercase letter, one lowercase letter,
// one number and one special character
export const isValidPassword = (password: string): boolean => {
  const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/
  return passwordRegex.test(password)
}

// Phone number validation (simple format)
export const isValidPhone = (phone: string): boolean => {
  const phoneRegex = /^\+?[\d\s-]{10,}$/
  return phoneRegex.test(phone)
}

// URL validation
export const isValidUrl = (url: string): boolean => {
  try {
    new URL(url)
    return true
  } catch {
    return false
  }
}

// File size validation (in bytes)
export const isValidFileSize = (size: number, maxSize: number): boolean => {
  return size <= maxSize
}

// File type validation
export const isValidFileType = (type: string, allowedTypes: string[]): boolean => {
  return allowedTypes.includes(type.toLowerCase())
}

// Form validation helper
export interface ValidationRule {
  required?: boolean
  minLength?: number
  maxLength?: number
  pattern?: RegExp
  custom?: (value: any) => boolean
  message: string
}

export interface ValidationResult {
  isValid: boolean
  errors: string[]
}

export const validateField = (value: any, rules: ValidationRule[]): ValidationResult => {
  const errors: string[] = []

  for (const rule of rules) {
    // Required check
    if (rule.required && !value) {
      errors.push(rule.message)
      continue
    }

    // Skip other validations if value is empty and not required
    if (!value && !rule.required) continue

    // String length checks
    if (typeof value === 'string') {
      if (rule.minLength && value.length < rule.minLength) {
        errors.push(rule.message)
      }
      if (rule.maxLength && value.length > rule.maxLength) {
        errors.push(rule.message)
      }
    }

    // Pattern check
    if (rule.pattern && !rule.pattern.test(value)) {
      errors.push(rule.message)
    }

    // Custom validation
    if (rule.custom && !rule.custom(value)) {
      errors.push(rule.message)
    }
  }

  return {
    isValid: errors.length === 0,
    errors,
  }
}

// Common validation rules
export const validationRules = {
  required: (message: string = 'This field is required'): ValidationRule => ({
    required: true,
    message,
  }),
  
  email: (message: string = 'Please enter a valid email address'): ValidationRule => ({
    pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    message,
  }),
  
  password: (message: string = 'Password must be at least 8 characters with uppercase, lowercase, number and special character'): ValidationRule => ({
    pattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/,
    message,
  }),
  
  phone: (message: string = 'Please enter a valid phone number'): ValidationRule => ({
    pattern: /^\+?[\d\s-]{10,}$/,
    message,
  }),
  
  minLength: (length: number, message: string = `Minimum ${length} characters required`): ValidationRule => ({
    minLength: length,
    message,
  }),
  
  maxLength: (length: number, message: string = `Maximum ${length} characters allowed`): ValidationRule => ({
    maxLength: length,
    message,
  }),
}

export default {
  isValidEmail,
  isValidPassword,
  isValidPhone,
  isValidUrl,
  isValidFileSize,
  isValidFileType,
  validateField,
  validationRules,
}