// Auto-generated by Cursor – Lawsuit Frontend
// Developer note: Do not edit this file directly unless necessary.

import { Routes, Route, Navigate, useParams } from 'react-router-dom'
import { useAuthStore } from './stores/authStore'
import { useCourtAdminStore } from './stores/courtAdminStore'

// Public Pages
import LandingPage from './pages/LandingPage'
import LoginPage from './pages/auth/LoginPage'
import AdminLoginPage from './pages/auth/AdminLoginPage'
import SuperAdminLoginPage from './pages/auth/SuperAdminLoginPage'
import AdministratorsPage from './pages/auth/AdministratorsPage'
import RegisterPage from './pages/auth/RegisterPage'
import ChangePasswordPage from './pages/auth/ChangePasswordPage'
import ForgotPasswordPage from './pages/auth/ForgotPasswordPage'
import CourtAdminRegisterPage from './pages/auth/CourtAdminRegisterPage'
import OtpVerifyPage from './pages/auth/OtpVerifyPage'
import PrivacyPolicyPage from './pages/PrivacyPolicyPage'
import TermsOfServicePage from './pages/TermsOfServicePage'
import UnderDevelopmentPlaceholder from './components/organisms/UnderDevelopmentPlaceholder'

// App Pages
import AppLayout from './layouts/AppLayout'
import HomePage from './pages/app/HomePage'
import SearchPage from './pages/app/SearchPage'
import LawyerDetailPage from './pages/app/LawyerDetailPage'
import BookingPage from './pages/app/BookingPage'
import AppointmentsPage from './pages/app/AppointmentsPage'
import CaseDetailPage from './pages/app/CaseDetailPage'
import WalletPage from './pages/app/WalletPage'
import WithdrawPage from './pages/app/WithdrawPage'
import ProfilePage from './pages/app/ProfilePage'
import AiChatPage from './components/organisms/AiChatPage'
import ViewCasePages from './pages/app/ViewCasePages'
import CaseDetailsClientPage from './pages/app/CaseDetailsClientPage'
import VideoConsultationPage from './pages/app/VideoConsultationPage'
import CallHistoryPage from './pages/app/CallHistoryPage'
import TeleLawPage from './pages/app/TeleLawPage'
import ReferralPage from './pages/app/ReferralPage'
import BankAccountsPage from './pages/app/BankAccountsPage'
import SubscriptionPage from './pages/app/SubscriptionPage'
import ReportIssuePage from './pages/app/ReportIssuePage'
import LegalUpdatesPage from './pages/app/LegalUpdatesPage'
// Admin Pages
import AdminLayout from './layouts/AdminLayout'
import TemplatesPage from './pages/admin/TemplatesPage'
import AdminDashboardPage from './pages/admin/AdminDashboardPage'
import AdminPayoutsPage from './pages/admin/AdminPayoutsPage'
import AdminUserModerationPage from './pages/admin/AdminUserModerationPage'
import AdminLegalUpdatesPage from './pages/admin/AdminLegalUpdatesPage'
import AdminReportsPage from './pages/admin/AdminReportsPage'
import AdminConsentsPage from './pages/admin/AdminConsentsPage'
import AdminCompliancePage from './pages/admin/AdminCompliancePage'
import AdminConfigPage from './pages/admin/AdminConfigPage'
import AdminCourtAdminsPage from './pages/admin/AdminCourtAdminsPage'
import AdminSalaryPage from './pages/admin/AdminSalaryPage'
import AdminCourtsPage from './pages/admin/AdminCourtsPage'
import AdminTeamPage from './pages/admin/AdminTeamPage'
import AdminWalletsPage from './pages/admin/AdminWalletsPage'
import AdminBankAccountsPage from './pages/admin/AdminBankAccountsPage'
import AdminLawyerActivityPage from './pages/admin/AdminLawyerActivityPage'
import AdminOrganizationActivityPage from './pages/admin/AdminOrganizationActivityPage'
import AdminCourtAdminActivityPage from './pages/admin/AdminCourtAdminActivityPage'
import AdminAnnouncementsPage from './pages/admin/AdminAnnouncementsPage'
import AdminLawyersPage from './pages/admin/AdminLawyersPage'
import AdminOrganizationsPage from './pages/admin/AdminOrganizationsPage'
import PaymentHistoryPage from './pages/app/PaymentHistoryPage'
import HelpCenterPage from './pages/HelpCenterPage'
import AboutPage from './pages/AboutPage'
import SettingsPage from './pages/app/SettingsPage'
import EkycPage from './pages/app/EkycPage'
import EkycDigilockerCallback from './pages/app/EkycDigilockerCallback'
import SignDocumentPage from './pages/app/SignDocumentPage'

// Lawyer Pages
import LawyerLayout from './layouts/LawyerLayout'
import LawyerHomePage from './pages/lawyer/LawyerHomePage'
import LawyerAppointments from './pages/lawyer/Appointments'
import LawyerProfilePage from './pages/lawyer/LawyerProfilePage'
import LexRateTable from './components/organisms/LexRatesTable'
import ViewCasePagesLawyer from './pages/lawyer/ViewCasePagesLawyer'
import CaseDetailsLawyerPage from './pages/lawyer/CaseDetailsLawyerPage'
import AgreementTemplatesPage from './pages/lawyer/AgreementTemplatesPage'
import LawyerMediatorSettingsPage from './pages/lawyer/LawyerMediatorSettingsPage'
import LawyerSalaryPage from './pages/lawyer/LawyerSalaryPage'
// Lawyer onboarding page retired — verification now lives in the lawyer's
// profile page (LawyerVerificationSection). Profile is the single home
// for verifying with a court admin.
import LawyerAvailabilityPage from './pages/lawyer/LawyerAvailabilityPage'
import LawyerClientDetailPage from './pages/lawyer/LawyerClientDetailPage'
// Mediation Pages
import MediationsPage from './pages/app/MediationsPage'
import MediationDetailPage from './pages/app/MediationDetailPage'
import NewMediationInvitePage from './pages/app/NewMediationInvitePage'
import MediationRoomPage from './pages/app/MediationRoomPage'
import MediationInviteAcceptPage from './pages/mediation/MediationInviteAcceptPage'
// The Phase-1 DRAFT mediation flow is fully retired. There is ONE
// canonical flow: the case lawyer sends the invite (immediate email +
// notification, no draft) and the respondent accepts at
// `/mediation/invite/:token`. MediationInitiatePage / MediationFlowList
// / MediationFlowDetail / MediationFlowInvite are no longer routed.
import MediatorProfilePage from './pages/lawyer/MediatorProfilePage'
// Court Admin Pages
import CourtAdminLayout from './layouts/CourtAdminLayout'
import CourtAdminLoginPage from './pages/auth/CourtAdminLoginPage'
import CourtAdminDashboardPage from './pages/courtAdmin/CourtAdminDashboardPage'
import VerifyLawyerPage from './pages/courtAdmin/VerifyLawyerPage'
import CourtAdminProfilePage from './pages/courtAdmin/CourtAdminProfilePage'
import OrganizationVerificationsPage from './pages/courtAdmin/OrganizationVerificationsPage'
import CourtAdminSalaryPage from './pages/courtAdmin/CourtAdminSalaryPage'

// Organization (Law Firm) Pages
import OrganizationLayout from './layouts/OrganizationLayout'
import OrganizationDashboardPage from './pages/organization/OrganizationDashboardPage'
import OrganizationProfilePage from './pages/organization/OrganizationProfilePage'
import OrganizationLawyersPage from './pages/organization/OrganizationLawyersPage'
import OrganizationRequestsPage from './pages/organization/OrganizationRequestsPage'
import OrganizationVerificationPage from './pages/organization/OrganizationVerificationPage'
import OrganizationSalaryPage from './pages/organization/OrganizationSalaryPage'
import OrganizationMySalaryPage from './pages/organization/OrganizationMySalaryPage'
// Shared (Client + Lawyer): standalone chat list and document AI workspace
import ChatListPage from './pages/shared/ChatListPage'
import DocumentAiPage from './pages/shared/DocumentAiPage'
import DocumentPreviewPage from './pages/shared/DocumentPreviewPage'
import CalendarPage from './pages/shared/CalendarPage'

// Client-side firm discovery
import FirmsListPage from './pages/app/firms/FirmsListPage'
import FirmDetailPage from './pages/app/firms/FirmDetailPage'
import MyFirmRequestsPage from './pages/app/firms/MyFirmRequestsPage'

// eKYC gate — required for any client-side action that touches money,
// case filings, mediation, or consultations.
import EkycGuard from './components/organisms/EkycGuard'

// Resolve the user's role with a localStorage fallback. Other stores
// (userStore, courtAdminStore) write to authStore.user via setState, so the
// in-memory value can flip briefly during a render. Storage is the canonical
// post-login source of truth until the next login/logout.
import storage from '@/utils/storage'
function useEffectiveRole(): string | undefined {
  const stateUser = useAuthStore((s) => s.user) as any
  if (stateUser?.role) return String(stateUser.role).toUpperCase()
  const stored = storage.getUserData<any>()
  return stored?.role ? String(stored.role).toUpperCase() : undefined
}

// Protected Route Component
const ProtectedRoute = ({ children }: { children: React.ReactNode }) => {
  const { isAuthenticated, user } = useAuthStore()
  if (!isAuthenticated) return <Navigate to="/auth/login" replace />
  // Forced-rotation guard: server flags admin-invited / reset accounts with
  // `mustChangePassword=true`. We bounce them to the change-password screen
  // until they rotate their password (which clears the flag server-side).
  if ((user as any)?.mustChangePassword) {
    return <Navigate to="/auth/change-password?force=1" replace />
  }
  return <>{children}</>
}

const CourtAdminProtectedRoute = ({ children }: { children: React.ReactNode }) => {
  const { isAuthenticated, user } = useCourtAdminStore()
  return isAuthenticated && user?.role === 'COURT_ADMIN' ? <>{children}</> : <Navigate to="/auth/court-admin-login" replace />
}

// Param-preserving redirect for the retired Phase-1+2 plural
// `mediations/:id` path. The single canonical mediation detail page
// lives at the singular `mediation/:id`; role decides whether that's
// under /app or /lawyer.
function MediationFlowIdRedirect() {
  const { id } = useParams()
  const role = useEffectiveRole()
  const base = role === 'LAWYER' ? '/lawyer' : '/app'
  return <Navigate to={`${base}/mediation/${id}`} replace />
}

const AppRoutes = () => {
  // Effective role with localStorage fallback. Use this for ALL role-based
  // route guards/redirects so a transient null/wrong user state doesn't bounce
  // an org user back to /app/home.
  const role = useEffectiveRole()

  return (
    <Routes>
      {/* Public Routes */}
      <Route path="/" element={<LandingPage />} />
      <Route path="/auth/login" element={<LoginPage />} />
      {/* Administrators hub — Court Admin + Super Admin entry points live
          here, behind a single button on the user-facing sign-in / sign-up. */}
      <Route path="/auth/administrators" element={<AdministratorsPage />} />
      <Route path="/auth/super-admin-login" element={<SuperAdminLoginPage />} />
      {/* Legacy paths — kept so existing bookmarks & email links still resolve. */}
      <Route path="/auth/admin-login" element={<AdminLoginPage />} />
      <Route path="/auth/court-admin-login" element={<CourtAdminLoginPage />} />
      <Route path="/auth/court-admin-register" element={<CourtAdminRegisterPage />} />
      <Route path="/auth/register" element={<RegisterPage />} />
      <Route path="/auth/forgot-password" element={<ForgotPasswordPage />} />
      {/* Change password route — accessible while authenticated. The
          ProtectedRoute guard auto-redirects users with `mustChangePassword`
          here with `?force=1`, so we don't wrap this route in it. */}
      <Route path="/auth/change-password" element={<ChangePasswordPage />} />
      <Route path="/auth/otp-verify" element={<OtpVerifyPage />} />
      <Route path="/privacy-policy" element={<PrivacyPolicyPage />} />
      <Route path="/terms-of-service" element={<TermsOfServicePage />} />
      <Route path="/about" element={<AboutPage />} />
      <Route path="/help" element={<HelpCenterPage />} />

      {/* Canonical mediation invite link (public; acts based on auth).
          The lawyer-initiated invite email links here with a path token.
          The retired Phase-1 query-param draft accept page is gone. */}
      <Route path="/mediation/invite/:token" element={<MediationInviteAcceptPage />} />

      {/* Universal document preview. Renders any uploaded asset URL using
          <embed type="application/pdf"> for PDFs (so Cloudinary `raw`
          URLs preview correctly regardless of HTTP Content-Type), <img>
          for images, and a download card for everything else. Mounted at
          the top level so every role can link to it without role-prefix
          churn (`/preview?url=…&name=…&mime=…`). */}
      <Route path="/preview" element={<DocumentPreviewPage />} />

      {/* Protected App Routes */}
      <Route
        path="/app"
        element={
          <ProtectedRoute>
            {role === 'LAWYER' ? (
              <Navigate to="/lawyer/dashboard" replace />
            ) : role === 'ADMIN' ? (
              <Navigate to="/admin/dashboard" replace />
            ) : role === 'ORGANIZATION' ? (
              <Navigate to="/organization/dashboard" replace />
            ) : (
              <AppLayout />
            )}
          </ProtectedRoute>
        }
      >
        <Route path="home" element={<HomePage />} />
        <Route path="calendar" element={<CalendarPage />} />
        <Route path="search" element={<SearchPage />} />
        <Route path="lawyers/:id" element={<LawyerDetailPage />} />
        {/* Booking, withdrawals, case filing, mediation initiation are all
            actions that move money or commit the user to legal proceedings —
            we require Aadhaar eKYC before allowing any of them. The guard
            renders a friendly explainer + Verify CTA for un-verified clients
            and is a no-op for non-CLIENT roles. */}
        <Route path="book/:lawyerId" element={
          <EkycGuard action="book a consultation"><BookingPage /></EkycGuard>
        } />
        <Route path="appointments" element={
          role === 'LAWYER' ? <Navigate to="/lawyer/appointments" replace /> : <AppointmentsPage />
        } />
        <Route path="wallet" element={<WalletPage />} />
        <Route path="withdraw" element={
          <EkycGuard action="withdraw money"><WithdrawPage /></EkycGuard>
        } />
        <Route path="cases" element={
          <EkycGuard action="file or manage cases"><ViewCasePages /></EkycGuard>
        } />
        <Route path="case/:caseId" element={
          <EkycGuard action="open this case"><CaseDetailsClientPage /></EkycGuard>
        } />
        <Route path="profile" element={<ProfilePage />} />
        <Route path="lex-rates" element={<LexRateTable />} />
        <Route path="tele-law" element={<TeleLawPage />} />
        <Route path="legal-eagle" element={<AiChatPage />} />
        <Route path="referral" element={<ReferralPage />} />
        <Route path="bank-accounts" element={<BankAccountsPage />} />
        <Route path="subscription" element={<SubscriptionPage />} />
        <Route path="report-issue" element={<ReportIssuePage />} />
        <Route path="legal-updates" element={<LegalUpdatesPage />} />
        <Route path="payments" element={<PaymentHistoryPage />} />
        <Route path="settings" element={<SettingsPage />} />
        <Route path="help" element={<HelpCenterPage />} />
        <Route path="about" element={<AboutPage />} />
        {/* Aadhaar eKYC — full-page version. CLIENT only (page renders an
            empty stub for non-clients). The on-card version lives on /app/profile. */}
        <Route path="ekyc" element={<EkycPage />} />
        {/* Landing page for the Surepass DigiLocker redirect — completes the
            verification after the user returns from DigiLocker. */}
        <Route path="ekyc/digilocker/callback" element={<EkycDigilockerCallback />} />
        {/* E-signature — a party signs a document via OTP. */}
        <Route path="sign/:id" element={<SignDocumentPage />} />
        <Route path="consultation/:appointmentId" element={
          <EkycGuard action="join the consultation"><VideoConsultationPage /></EkycGuard>
        } />
        <Route path="call-history" element={<CallHistoryPage />} />

        {/* Mediation (client) — gated because mediation creates a legal record */}
        <Route path="mediations" element={<MediationsPage />} />
        <Route path="mediation/new" element={
          <EkycGuard action="initiate a mediation"><NewMediationInvitePage /></EkycGuard>
        } />
        {/* Flow consolidated → ONE canonical mediation flow lives on the
            singular `/app/mediation/*` paths. The old Phase 1+2 plural
            paths now redirect so bookmarks / deep-links keep working. */}
        <Route path="mediations/flow" element={<Navigate to="/app/mediations" replace />} />
        <Route path="mediations/new" element={<Navigate to="/app/mediation/new" replace />} />
        <Route path="mediations/:id" element={<MediationFlowIdRedirect />} />
        <Route path="mediation/:id" element={
          <EkycGuard action="open this mediation"><MediationDetailPage /></EkycGuard>
        } />
        <Route path="mediation/:id/room" element={
          <EkycGuard action="join the mediation room"><MediationRoomPage /></EkycGuard>
        } />

        {/* Law firms (organization) discovery & booking */}
        <Route path="firms" element={<FirmsListPage />} />
        <Route path="firms/:id" element={<FirmDetailPage />} />
        {/* Legacy path — firm requests are now a tab inside Appointments
            (Lawyer | Firm switcher). Redirect preserves any existing
            bookmarks / push-notification deep-links. */}
        <Route path="firms-requests" element={<Navigate to="/app/appointments?view=firm" replace />} />

        {/* Standalone chat list + document AI (mobile-app parity) */}
        <Route path="chats" element={<ChatListPage />} />
        <Route path="document-ai" element={
          <EkycGuard action="use Document AI"><DocumentAiPage /></EkycGuard>
        } />

        <Route path="under-development" element={<UnderDevelopmentPlaceholder />} />
      </Route>

      {/* Organization (Law Firm) Routes */}
      <Route
        path="/organization"
        element={
          <ProtectedRoute>
            {role === 'ORGANIZATION' ? (
              <OrganizationLayout />
            ) : (
              <Navigate to="/app/home" replace />
            )}
          </ProtectedRoute>
        }
      >
        <Route index element={<Navigate to="dashboard" replace />} />
        <Route path="dashboard" element={<OrganizationDashboardPage />} />
        <Route path="calendar" element={<CalendarPage />} />
        <Route path="profile" element={<OrganizationProfilePage />} />
        <Route path="lawyers" element={<OrganizationLawyersPage />} />
        <Route path="salary" element={<OrganizationSalaryPage />} />
        {/* Org head's own performance-salary view (paid by the platform) */}
        <Route path="my-salary" element={<OrganizationMySalaryPage />} />
        <Route path="requests" element={<OrganizationRequestsPage />} />
        <Route path="verification" element={<OrganizationVerificationPage />} />
        {/* Unified WhatsApp-style chat — same page as /app/chats and
            /lawyer/chats; server-side rolled-up list is JWT-filtered so the
            org head sees their own conversations. */}
        <Route path="chats" element={<ChatListPage />} />
        {/* Document AI workspace — same component as /app/document-ai.
            Mounted here so chat doc-chips can deep-link via
            `/organization/document-ai?documentId=…` instead of being
            bounced to a /app route the org layout doesn't render. */}
        <Route path="document-ai" element={<DocumentAiPage />} />
        {/* Legal Eagle — AI legal chat. Backed by /api/v1/model/chat
            which already accepts any authenticated role. Reuses the
            same AiChatPage the client + lawyer routes mount. */}
        <Route path="legal-eagle" element={<AiChatPage />} />
      </Route>

      {/* Admin Routes */}
      <Route
        path="/admin"
        element={
          <ProtectedRoute>
            {role === 'ADMIN' ? (
              <AdminLayout />
            ) : (
              <Navigate to="/app/home" replace />
            )}
          </ProtectedRoute>
        }
      >
        <Route path="templates" element={<TemplatesPage />} />
        <Route path="dashboard" element={<AdminDashboardPage />} />
        <Route path="moderation" element={<AdminUserModerationPage />} />
        <Route path="lawyers" element={<AdminLawyersPage />} />
        <Route path="organizations" element={<AdminOrganizationsPage />} />
        <Route path="payouts" element={<AdminPayoutsPage />} />
        <Route path="court-admins" element={<AdminCourtAdminsPage />} />
        <Route path="legal-updates" element={<AdminLegalUpdatesPage />} />
        <Route path="reports" element={<AdminReportsPage />} />
        {/* Consent / provenance audit — every consent event captured platform-wide. */}
        <Route path="consents" element={<AdminConsentsPage />} />
        {/* Compliance report pack — SUPER_ADMIN CSV exports. */}
        <Route path="compliance" element={<AdminCompliancePage />} />
        <Route path="settings" element={<AdminConfigPage />} />
        <Route path="salary" element={<AdminSalaryPage />} />
        <Route path="courts" element={<AdminCourtsPage />} />
        <Route path="team" element={<AdminTeamPage />} />
        <Route path="wallets" element={<AdminWalletsPage />} />
        <Route path="bank-accounts" element={<AdminBankAccountsPage />} />
        {/* Monthly activity / performance logs */}
        <Route path="lawyers/:id/activity" element={<AdminLawyerActivityPage />} />
        <Route path="organizations/:id/activity" element={<AdminOrganizationActivityPage />} />
        <Route path="court-admins/:id/activity" element={<AdminCourtAdminActivityPage />} />
        <Route path="announcements" element={<AdminAnnouncementsPage />} />
        {/* Unified WhatsApp-style chat — admins see conversations they're a
            participant in (e.g. support threads). Same page as the other
            roles, the server filters by JWT. */}
        <Route path="chats" element={<ChatListPage />} />
        {/* Document AI workspace — admins occasionally need to open docs
            shared from chat support threads. */}
        <Route path="document-ai" element={<DocumentAiPage />} />

        <Route path="under-development" element={<UnderDevelopmentPlaceholder />} />
      </Route>

      {/* Lawyer Routes */}
      <Route
        path="/lawyer"
        element={
          <ProtectedRoute>
            {role === 'LAWYER' ? (
              <LawyerLayout />
            ) : (
              <Navigate to="/app/home" replace />
            )}
          </ProtectedRoute>
        }
      >
        {/* <Route index element={<Navigate to="appointments" replace />} /> */}
        <Route index element={<Navigate to="dashboard" replace />} />
        <Route path="dashboard" element={<LawyerHomePage />} />
        <Route path="calendar" element={<CalendarPage />} />
        <Route path="appointments" element={<LawyerAppointments />} />
        <Route path="case/:caseId" element={<CaseDetailsLawyerPage />} />
        <Route path="cases" element={<ViewCasePagesLawyer />} />
        <Route path="profile" element={<LawyerProfilePage />} />
        <Route path="agreement-templates" element={<AgreementTemplatesPage />} />
        <Route path="mediator-settings" element={<LawyerMediatorSettingsPage />} />
        <Route path="salary" element={<LawyerSalaryPage />} />
        {/* /lawyer/onboarding retired — redirect lingering bookmarks to
            /lawyer/profile where the verification section lives. */}
        <Route path="onboarding" element={<Navigate to="/lawyer/profile" replace />} />
        <Route path="availability" element={<LawyerAvailabilityPage />} />
        <Route path="client/:clientId" element={<LawyerClientDetailPage />} />
        <Route path="settings" element={<SettingsPage />} />
        <Route path="help" element={<HelpCenterPage />} />
        <Route path="about" element={<AboutPage />} />
        <Route path="mediations" element={<MediationsPage />} />
        {/* Lawyer-initiated mediation invite from the Case (canonical
            flow step 1). Server records initiator client = case client,
            initiator lawyer = this lawyer. */}
        <Route path="mediation/new" element={<NewMediationInvitePage />} />
        <Route path="mediation/:id" element={<MediationDetailPage />} />
        <Route path="mediation/:id/room" element={<MediationRoomPage />} />
        {/* Consolidated → ONE canonical mediation flow. The retired
            plural Phase-1+2 paths redirect so deep-links keep resolving. */}
        <Route path="mediations/flow" element={<Navigate to="/lawyer/mediations" replace />} />
        <Route path="mediations/:id" element={<MediationFlowIdRedirect />} />
        {/* Lawyer's mediator-profile (opt-in to the panel). */}
        <Route path="mediator-profile" element={<MediatorProfilePage />} />
        <Route path="consultation/:appointmentId" element={<VideoConsultationPage />} />
        <Route path="call-history" element={<CallHistoryPage />} />

        <Route path="wallet" element={<WalletPage />} />
        <Route path="withdraw" element={<WithdrawPage />} />
        <Route path="legal-eagle" element={<AiChatPage />} />
        <Route path="referral" element={<ReferralPage />} />
        <Route path="bank-accounts" element={<BankAccountsPage />} />
        <Route path="subscription" element={<SubscriptionPage />} />
        <Route path="report-issue" element={<ReportIssuePage />} />
        <Route path="legal-updates" element={<LegalUpdatesPage />} />
        <Route path="payments" element={<PaymentHistoryPage />} />
        {/* Standalone chat list + document AI workspace (mobile-app parity) */}
        <Route path="chats" element={<ChatListPage />} />
        <Route path="document-ai" element={<DocumentAiPage />} />
        <Route path="under-development" element={<UnderDevelopmentPlaceholder />} />
      </Route>

      {/* Court Admin Routes */}
      <Route
        path="/court-admin"
        element={
          <CourtAdminProtectedRoute>
            <CourtAdminLayout />
          </CourtAdminProtectedRoute>
        }
      >
        <Route index element={<Navigate to="dashboard" replace />} />
        <Route path="dashboard" element={<CourtAdminDashboardPage />} />
        <Route path="verify/:lawyerId" element={<VerifyLawyerPage />} />
        <Route path="organization-verifications" element={<OrganizationVerificationsPage />} />
        <Route path="salary" element={<CourtAdminSalaryPage />} />
        <Route path="profile" element={<CourtAdminProfilePage />} />
        {/* Document AI — court admins rarely need this but a chat doc chip
            deep-links here when they happen to receive one in a support
            thread, so we mount it to prevent a dead-link redirect. */}
        <Route path="document-ai" element={<DocumentAiPage />} />
      </Route>

      {/* Fallback route */}
      <Route path="*" element={<Navigate to="/" replace />} />
    </Routes>
  )
}

export default AppRoutes