// Auto-generated by Cursor – Lawsuit Frontend
// Developer note: Do not edit this file directly unless necessary.

import { Routes, Route, Navigate } from 'react-router-dom'
import { useAuthStore } from './stores/authStore'
import { useCourtAdminStore } from './stores/courtAdminStore'

// Public Pages
import LandingPage from './pages/LandingPage'
import LoginPage from './pages/auth/LoginPage'
import AdminLoginPage from './pages/auth/AdminLoginPage'
import RegisterPage from './pages/auth/RegisterPage'
import OtpVerifyPage from './pages/auth/OtpVerifyPage'
import PrivacyPolicyPage from './pages/PrivacyPolicyPage'
import TermsOfServicePage from './pages/TermsOfServicePage'
import UnderDevelopmentPlaceholder from './components/organisms/UnderDevelopmentPlaceholder'

// App Pages
import AppLayout from './layouts/AppLayout'
import HomePage from './pages/app/HomePage'
import SearchPage from './pages/app/SearchPage'
import LawyerDetailPage from './pages/app/LawyerDetailPage'
import BookingPage from './pages/app/BookingPage'
import AppointmentsPage from './pages/app/AppointmentsPage'
// import CasesListPage from './pages/app/CasesListPage'
import CaseDetailPage from './pages/app/CaseDetailPage'
import WalletPage from './pages/app/WalletPage'
import WithdrawPage from './pages/app/WithdrawPage'
import ProfilePage from './pages/app/ProfilePage'
import AiChatPage from './components/organisms/AiChatPage'
import ViewCasePages from './pages/app/ViewCasePages'
import CaseDetailsClientPage from './pages/app/CaseDetailsClientPage'
import VideoConsultationPage from './pages/app/VideoConsultationPage'
import CallHistoryPage from './pages/app/CallHistoryPage'
import TeleLawPage from './pages/app/TeleLawPage'
// Admin Pages
import AdminLayout from './layouts/AdminLayout'
import TemplatesPage from './pages/admin/TemplatesPage'
import AdminDashboardPage from './pages/admin/AdminDashboardPage'
import UserManagementPage from './pages/admin/UserManagementPage'

// Lawyer Pages
import LawyerLayout from './layouts/LawyerLayout'
import LawyerHomePage from './pages/lawyer/LawyerHomePage'
import LawyerAppointments from './pages/lawyer/Appointments'
import LawyerProfilePage from './pages/lawyer/LawyerProfilePage'
import LexRateTable from './components/organisms/LexRatesTable'
import ViewCasePagesLawyer from './pages/lawyer/ViewCasePagesLawyer'
import CaseDetailsLawyerPage from './pages/lawyer/CaseDetailsLawyerPage'
import AgreementTemplatesPage from './pages/lawyer/AgreementTemplatesPage'
import LawyerMediatorSettingsPage from './pages/lawyer/LawyerMediatorSettingsPage'
// Mediation Pages
import MediationsPage from './pages/app/MediationsPage'
import MediationDetailPage from './pages/app/MediationDetailPage'
import NewMediationInvitePage from './pages/app/NewMediationInvitePage'
import MediationRoomPage from './pages/app/MediationRoomPage'
import MediationInviteAcceptPage from './pages/mediation/MediationInviteAcceptPage'
// Court Admin Pages
import CourtAdminLayout from './layouts/CourtAdminLayout'
import CourtAdminLoginPage from './pages/auth/CourtAdminLoginPage'
import CourtAdminDashboardPage from './pages/courtAdmin/CourtAdminDashboardPage'
import VerifyLawyerPage from './pages/courtAdmin/VerifyLawyerPage'
import CourtAdminProfilePage from './pages/courtAdmin/CourtAdminProfilePage'



// Protected Route Component
const ProtectedRoute = ({ children }: { children: React.ReactNode }) => {
  const { isAuthenticated } = useAuthStore()
  return isAuthenticated ? <>{children}</> : <Navigate to="/auth/login" replace />
}

const CourtAdminProtectedRoute = ({ children }: { children: React.ReactNode }) => {
  const { isAuthenticated, user } = useCourtAdminStore()
  return isAuthenticated && user?.role === 'COURT_ADMIN' ? <>{children}</> : <Navigate to="/auth/court-admin-login" replace />
}

const AppRoutes = () => {
  const { user } = useAuthStore()

  return (
    <Routes>
      {/* Public Routes */}
      <Route path="/" element={<LandingPage />} />
      <Route path="/auth/login" element={<LoginPage />} />
      <Route path="/auth/admin-login" element={<AdminLoginPage />} />
      <Route path="/auth/court-admin-login" element={<CourtAdminLoginPage />} />
      <Route path="/auth/register" element={<RegisterPage />} />
      <Route path="/auth/otp-verify" element={<OtpVerifyPage />} />
      <Route path="/privacy-policy" element={<PrivacyPolicyPage />} />
      <Route path="/terms-of-service" element={<TermsOfServicePage />} />

      {/* Mediation invite link (public; acts based on auth) */}
      <Route path="/mediation/invite/:token" element={<MediationInviteAcceptPage />} />

      {/* Protected App Routes */}
      <Route
        path="/app"
        element={
          <ProtectedRoute>
            {user?.role === 'LAWYER' ? (
              <Navigate to="/lawyer/dashboard" replace />
            ) : user?.role === 'ADMIN' ? (
              <Navigate to="/admin/dashboard" replace />
            ) : (
              <AppLayout />
            )}
          </ProtectedRoute>
        }
      >
        <Route path="home" element={<HomePage />} />
        <Route path="search" element={<SearchPage />} />
        <Route path="lawyers/:id" element={<LawyerDetailPage />} />
        <Route path="book/:lawyerId" element={<BookingPage />} />
        <Route path="appointments" element={
          user?.role === 'LAWYER' ? <Navigate to="/lawyer/appointments" replace /> : <AppointmentsPage />
        } />
        <Route path="wallet" element={<WalletPage />} />
        <Route path="withdraw" element={<WithdrawPage />} />
        <Route path="cases" element={<ViewCasePages />} />
        <Route path="case/:caseId" element={<CaseDetailsClientPage />} />
        <Route path="profile" element={<ProfilePage />} />
        <Route path="lex-rates" element={<LexRateTable />} />
        <Route path="tele-law" element={<TeleLawPage />} />
        <Route path="legal-eagle" element={<AiChatPage />} />
        <Route path="consultation/:appointmentId" element={<VideoConsultationPage />} />
        <Route path="call-history" element={<CallHistoryPage />} />

        {/* Mediation (client) */}
        <Route path="mediations" element={<MediationsPage />} />
        <Route path="mediation/new" element={<NewMediationInvitePage />} />
        <Route path="mediation/:id" element={<MediationDetailPage />} />
        <Route path="mediation/:id/room" element={<MediationRoomPage />} />

        <Route path="under-development" element={<UnderDevelopmentPlaceholder />} />
      </Route>

      {/* Admin Routes */}
      <Route
        path="/admin"
        element={
          <ProtectedRoute>
            {user?.role === 'ADMIN' ? (
              <AdminLayout />
            ) : (
              <Navigate to="/app/home" replace />
            )}
          </ProtectedRoute>
        }
      >
        <Route path="templates" element={<TemplatesPage />} />
        <Route path="dashboard" element={<AdminDashboardPage />} />
        <Route path="userManagement" element={<UserManagementPage />} />


        <Route path="under-development" element={<UnderDevelopmentPlaceholder />} />
      </Route>

      {/* Lawyer Routes */}
      <Route
        path="/lawyer"
        element={
          <ProtectedRoute>
            {user?.role === 'LAWYER' ? (
              <LawyerLayout />
            ) : (
              <Navigate to="/app/home" replace />
            )}
          </ProtectedRoute>
        }
      >
        {/* <Route index element={<Navigate to="appointments" replace />} /> */}
        <Route index element={<Navigate to="dashboard" replace />} />
        <Route path="dashboard" element={<LawyerHomePage />} />
        <Route path="appointments" element={<LawyerAppointments />} />
        <Route path="case/:caseId" element={<CaseDetailsLawyerPage />} />
        <Route path="cases" element={<ViewCasePagesLawyer />} />
        <Route path="profile" element={<LawyerProfilePage />} />
        <Route path="agreement-templates" element={<AgreementTemplatesPage />} />
        <Route path="mediator-settings" element={<LawyerMediatorSettingsPage />} />
        <Route path="mediations" element={<MediationsPage />} />
        <Route path="mediation/:id" element={<MediationDetailPage />} />
        <Route path="mediation/:id/room" element={<MediationRoomPage />} />
        <Route path="consultation/:appointmentId" element={<VideoConsultationPage />} />
        <Route path="call-history" element={<CallHistoryPage />} />

        <Route path="wallet" element={<WalletPage />} />
        <Route path="withdraw" element={<WithdrawPage />} />
        <Route path="legal-eagle" element={<AiChatPage />} />
        <Route path="under-development" element={<UnderDevelopmentPlaceholder />} />
      </Route>

      {/* Court Admin Routes */}
      <Route
        path="/court-admin"
        element={
          <CourtAdminProtectedRoute>
            <CourtAdminLayout />
          </CourtAdminProtectedRoute>
        }
      >
        <Route index element={<Navigate to="dashboard" replace />} />
        <Route path="dashboard" element={<CourtAdminDashboardPage />} />
        <Route path="verify/:lawyerId" element={<VerifyLawyerPage />} />
        <Route path="profile" element={<CourtAdminProfilePage />} />
      </Route>

      {/* Fallback route */}
      <Route path="*" element={<Navigate to="/" replace />} />
    </Routes>
  )
}

export default AppRoutes