// Auto-generated by Cursor – Lawsuit Frontend
// Developer note: Do not edit this file directly unless necessary.

import { http, HttpResponse } from 'msw'
import type { User } from '../types'
import { mockLawyers, specializations, locations, languages } from './mockData'

interface SearchParams {
  q?: string
  location?: string
  specialization?: string
  maxFee?: string
  page?: string
  limit?: string
}

const mockUsers: { [key: string]: User } = {
  'user_001': {
    id: 'user_001',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'client'
  },
  'user_002': {
    id: 'user_002',
    name: 'Jane Lawyer',
    email: 'jane@example.com',
    role: 'lawyer'
  }
  ,
  'admin_001': {
    id: 'admin_001',
    name: 'Site Admin',
    email: 'admin@example.com',
    role: 'admin'
  }
}

const mockTokens: { [key: string]: string } = {
  'user_001': 'mock_token_001',
  'user_002': 'mock_token_002'
  ,
  'admin_001': 'mock_token_admin'
}

// Simple in-memory appointments store for dev/testing
interface MockAppointment {
  id: string
  lawyerId: string
  lawyer?: any
  datetime: string // ISO
  paymentId?: string
  status: 'upcoming' | 'completed' | 'cancelled'
  agreementUrl: string
}

const mockAppointments: MockAppointment[] = []

// Simple in-memory cases store
interface MockCase {
  id: string
  title: string
  lawyerId: string
  lawyer?: any
  createdAt: string
  status?: 'open' | 'closed' | 'rejected'
  details?: string
}

const mockCases: MockCase[] = []

// Simple mock notifications
interface MockNotification {
  id: string
  title: string
  body?: string
  read?: boolean
  createdAt: string
}

const mockNotifications: MockNotification[] = [
  { id: 'n1', title: 'Welcome to Lawsuit', body: 'Thanks for joining our platform', read: false, createdAt: new Date().toISOString() },
]

// Simple wallet model derived from appointments/payments
interface MockWalletTx {
  id: string
  type: 'credit' | 'debit' | 'giftcard' | 'cashback'
  amount: number
  meta?: any
  createdAt: string
}

const mockWallet: { balance: number; transactions: MockWalletTx[] } = {
  balance: 0,
  transactions: [],
}

// initialize wallet balance & transactions from existing appointments that have paymentId
const _initWalletFromAppointments = () => {
  const txs: MockWalletTx[] = []
  let balance = 0

  mockAppointments
    .filter(a => a.paymentId && a.lawyer?.fee)
    .forEach(a => {
      const fee = a.lawyer.fee || 0
  // appointment transaction (full fee) - use a random tx id for privacy
  txs.push({ id: `tx_${Math.random().toString(36).slice(2,9)}`, type: 'credit', amount: fee, meta: { appointmentId: a.id, lawyerId: a.lawyer.id }, createdAt: new Date(a.datetime).toISOString() })
      // refund 30% to wallet
      const refundAmount = Math.round(fee * 0.3 * 100) / 100
      if (refundAmount > 0) {
        balance += refundAmount
        txs.push({ id: `tx_refund_${a.id}`, type: 'cashback', amount: refundAmount, meta: { appointmentId: a.id, lawyerId: a.lawyer.id, kind: 'cashback' }, createdAt: new Date(a.datetime).toISOString() })
      }
    })

  // newest-first
  mockWallet.balance = balance
  mockWallet.transactions = txs.reverse()
}

_initWalletFromAppointments()

export const handlers = [
  // Auth endpoints
  http.post('/api/auth/login', async ({ request }) => {
    const _body = await request.json()
    const { email, password } = _body as any
    
    if (!email || !password) {
      return new HttpResponse(
        JSON.stringify({ message: 'Email and password are required' }),
        { status: 400 }
      )
    }

    const user = Object.values(mockUsers).find(u => u.email === email)
    if (!user) {
      return new HttpResponse(
        JSON.stringify({ message: 'Invalid credentials' }),
        { status: 401 }
      )
    }

    return HttpResponse.json({
      user,
      token: mockTokens[user.id]
    })
  }),

  http.post('/api/auth/register', async ({ request }) => {
    const _body = await request.json()
    const { name, email, password, role } = _body as any

    if (!name || !email || !password || !role) {
      return new HttpResponse(
        JSON.stringify({ message: 'All fields are required' }),
        { status: 400 }
      )
    }

    if (Object.values(mockUsers).some(u => u.email === email)) {
      return new HttpResponse(
        JSON.stringify({ message: 'Email already exists' }),
        { status: 400 }
      )
    }

    const userId = `user_${Date.now()}`
    const user: User = { id: userId, name, email, role }
    mockUsers[userId] = user

    return HttpResponse.json({
      success: true,
      userId
    })
  }),

  http.post('/api/auth/verify-otp', async ({ request }) => {
    const _body = await request.json()
    const { userId, otp } = _body as any

    if (!userId || !otp) {
      return new HttpResponse(
        JSON.stringify({ message: 'User ID and OTP are required' }),
        { status: 400 }
      )
    }

    const user = mockUsers[userId]
    if (!user) {
      return new HttpResponse(
        JSON.stringify({ message: 'User not found' }),
        { status: 404 }
      )
    }

    // Mock OTP verification (any 6-digit code is valid)
    if (!/^\d{6}$/.test(otp)) {
      return new HttpResponse(
        JSON.stringify({ message: 'Invalid OTP' }),
        { status: 400 }
      )
    }

    return HttpResponse.json({
      user,
      token: mockTokens[userId] || `mock_token_${userId}`
    })
  }),

  // Lawyer endpoints
  http.get('/api/lawyers', ({ request }) => {
    const url = new URL(request.url)
    const searchParams = Object.fromEntries(url.searchParams)
    
    let filteredLawyers = [...mockLawyers]

    // Apply search query
    if (searchParams.q) {
      const query = searchParams.q.toLowerCase()
      filteredLawyers = filteredLawyers.filter(lawyer => 
        lawyer.name.toLowerCase().includes(query) ||
        lawyer.specialization.some(s => s.toLowerCase().includes(query))
      )
    }

    // Apply location filter
    if (searchParams.location) {
      filteredLawyers = filteredLawyers.filter(lawyer => 
        lawyer.location === searchParams.location
      )
    }

    // Apply specialization filter
    if (searchParams.specialization) {
      filteredLawyers = filteredLawyers.filter(lawyer => 
        lawyer.specialization.includes(searchParams.specialization)
      )
    }

    // Apply max fee filter
    if (searchParams.maxFee) {
      const maxFee = parseInt(searchParams.maxFee)
      if (!isNaN(maxFee)) {
        filteredLawyers = filteredLawyers.filter(lawyer => 
          lawyer.fee <= maxFee
        )
      }
    }

    // Apply pagination
    const page = parseInt(searchParams.page || '1')
    const limit = parseInt(searchParams.limit || '10')
    const start = (page - 1) * limit
    const end = start + limit
    const paginatedLawyers = filteredLawyers.slice(start, end)

    return HttpResponse.json({
      data: paginatedLawyers,
      total: filteredLawyers.length,
      page,
      limit,
      filters: {
        specializations,
        locations,
        languages
      }
    })
  }),

  http.get('/api/lawyers/:id', ({ params }) => {
    const { id } = params
    const lawyer = mockLawyers.find(l => l.id === id)

    if (!lawyer) {
      return new HttpResponse(
        JSON.stringify({ message: 'Lawyer not found' }),
        { status: 404 }
      )
    }

    return HttpResponse.json({ data: lawyer })
  })

  // Appointments endpoints (in-memory)
  ,http.post('/api/appointments', async ({ request }) => {
    const _body = await request.json()
    const { lawyerId, datetime, paymentId } = _body as any
    if (!lawyerId || !datetime) {
      return new HttpResponse(JSON.stringify({ message: 'Missing fields' }), { status: 400 })
    }

    const appointmentId = `appt_${Date.now()}`
    const lawyer = mockLawyers.find(l => l.id === lawyerId)
    const appt = {
      id: appointmentId,
      lawyerId,
      lawyer: lawyer ?? null,
      datetime,
      paymentId: paymentId ?? null,
      status: 'upcoming' as MockAppointment['status'],
      agreementUrl: `https://www.orimi.com/pdf-test.pdf` // mock agreement URL

    }
    mockAppointments.push(appt)

    // Create a notification for the new appointment so users see it immediately in the UI
    const notif = {
      id: `n_${Date.now()}`,
      title: `Appointment confirmed with ${lawyer?.name ?? 'your lawyer'}`,
      body: `Your consultation is scheduled on ${new Date(datetime).toLocaleString()}. Join here: https://meet.example.com/${appointmentId}`,
      read: false,
      createdAt: new Date().toISOString(),
    }
    // add to the front so it appears newest-first
    mockNotifications.unshift(notif)

    // If this appointment included a payment, record an appointment transaction
    // (full fee) and refund 30% of the lawyer fee to the wallet as a refund tx.
    if (paymentId && lawyer?.fee) {
      const fee = lawyer.fee || 0
      // appointment transaction
      const apptTx: MockWalletTx = {
        id: `tx_${Math.random().toString(36).slice(2,9)}`,
        type: 'credit',
        amount: fee,
        meta: { appointmentId: appointmentId, lawyerId },
        createdAt: new Date().toISOString(),
      }
      mockWallet.transactions.unshift(apptTx)

      // refund 30% to wallet
      const refundAmount = Math.round(fee * 0.3 * 100) / 100
      if (refundAmount > 0) {
        mockWallet.balance += refundAmount
        const refundTx: MockWalletTx = {
          id: `tx_cashback_${Date.now()}`,
          type: 'cashback',
          amount: refundAmount,
          meta: { appointmentId: appointmentId, lawyerId, kind: 'cashback' },
          createdAt: new Date().toISOString(),
        }
        mockWallet.transactions.unshift(refundTx)
      }
    }

    return HttpResponse.json({ data: appt })
  })

  ,http.get('/api/appointments', () => {
    // Return all appointments for the current mocked user
    return HttpResponse.json({ data: mockAppointments })
  })

  // Wallet endpoints
  ,http.get('/api/wallet', () => {
    return HttpResponse.json({ data: { balance: mockWallet.balance, transactions: mockWallet.transactions } })
  })

  ,http.post('/api/wallet/buy-giftcard', async ({ request }) => {
    const body = await request.json()
    const { amount, cardType } = body as any
    if (typeof amount !== 'number' || amount <= 0) {
      return new HttpResponse(JSON.stringify({ message: 'Invalid amount' }), { status: 400 })
    }

    if (mockWallet.balance < amount) {
      return new HttpResponse(JSON.stringify({ message: 'Insufficient balance' }), { status: 400 })
    }

  mockWallet.balance -= amount
  const tx: MockWalletTx = { id: `tx_${Math.random().toString(36).slice(2,9)}`, type: 'debit', amount, meta: { cardType, kind: 'giftcard' }, createdAt: new Date().toISOString() }
  mockWallet.transactions.unshift(tx)

    return HttpResponse.json({ data: tx })
  })

  // Notifications
  ,http.get('/api/notifications', () => {
    // return all notifications
    return HttpResponse.json({ data: mockNotifications })
  })

  ,http.patch('/api/notifications/:id/read', ({ params }) => {
    const { id } = params
    const n = mockNotifications.find(x => x.id === id)
    if (!n) return new HttpResponse(JSON.stringify({ message: 'Not found' }), { status: 404 })
    n.read = true
    return HttpResponse.json({ data: n })
  })

  ,http.patch('/api/notifications/mark-all', () => {
    mockNotifications.forEach(n => { n.read = true })
    return HttpResponse.json({ success: true })
  })

  // Patch appointment status (e.g., reject)
  ,http.patch('/api/appointments/:id', async ({ params, request }) => {
    const { id } = params
    const body = await request.json().catch(() => ({}))
    const { status } = body as any
    const appt = mockAppointments.find(a => a.id === id)
    if (!appt) {
      return new HttpResponse(JSON.stringify({ message: 'Appointment not found' }), { status: 404 })
    }
    if (status) {
      // accept common statuses; if rejected, set accordingly
      appt.status = status as any
    }
    return HttpResponse.json({ data: appt })
  })

  // Create case from an accepted appointment
  ,http.post('/api/cases', async ({ request }) => {
    const body = await request.json()
    const { title, lawyerId, details } = body as any
    if (!lawyerId) {
      return new HttpResponse(JSON.stringify({ message: 'lawyerId is required' }), { status: 400 })
    }
    const caseId = `case_${Date.now()}`
    const lawyer = mockLawyers.find(l => l.id === lawyerId) ?? null
    const c: MockCase = {
      id: caseId,
      title: title ?? `Case handled by ${lawyer?.name ?? lawyerId}`,
      lawyerId,
      lawyer,
      createdAt: new Date().toISOString(),
      status: 'open',
      details: details ?? ''
    }
    // attach optional arrays for frontend rendering
    ;(c as any).tasks = [
      { id: `${caseId}_task_1`, title: 'Provide ID proof to advocate', completed: false, createdBy: 'lawyer' },
      { id: `${caseId}_task_2`, title: 'Sign and return agreement', completed: false, createdBy: 'lawyer' }
    ]
    ;(c as any).timeline = [
      { id: `${caseId}_tl_1`, title: 'Case created', date: new Date().toISOString(), description: 'Case was created after appointment acceptance' }
    ]
    ;(c as any).hearings = []
    ;(c as any).documents = []
    mockCases.unshift(c)
    return HttpResponse.json({ data: c })
  })

  ,http.get('/api/cases', () => {
    return HttpResponse.json({ data: mockCases })
  })
  // Get case by id
  ,http.get('/api/cases/:id', ({ params }) => {
    const { id } = params
    const c = mockCases.find(x => x.id === id)
    if (!c) return new HttpResponse(JSON.stringify({ message: 'Case not found' }), { status: 404 })
    return HttpResponse.json({ data: c })
  })
]