// Auto-generated by Cursor – Lawsuit Frontend
// Developer note: Do not edit this file directly unless necessary.

import { setupWorker, rest } from 'msw'
import type { User } from '@/types'

const mockUsers: { [key: string]: User } = {
  'user_001': {
    id: 'user_001',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'client',
    avatar: null
  },
  'user_002': {
    id: 'user_002',
    name: 'Jane Lawyer',
    email: 'jane@example.com',
    role: 'lawyer',
    avatar: null
  }
}

const mockTokens: { [key: string]: string } = {
  'user_001': 'mock_token_001',
  'user_002': 'mock_token_002'
}

// Create handlers
const handlers = [
  // Auth endpoints
  rest.post('/api/auth/login', async (req, res, ctx) => {
    const { email, password } = await req.json()
    
    // Mock validation
    if (!email || !password) {
      return res(
        ctx.status(400),
        ctx.json({ message: 'Email and password are required' })
      )
    }

    // Mock user lookup
    const user = Object.values(mockUsers).find(u => u.email === email)
    if (!user) {
      return res(
        ctx.status(401),
        ctx.json({ message: 'Invalid credentials' })
      )
    }

    return res(
      ctx.status(200),
      ctx.json({
        user,
        token: mockTokens[user.id]
      })
    )
  }),

  rest.post('/api/auth/register', async (req, res, ctx) => {
    const { name, email, password, role } = await req.json()

    // Mock validation
    if (!name || !email || !password || !role) {
      return res(
        ctx.status(400),
        ctx.json({ message: 'All fields are required' })
      )
    }

    // Mock email exists check
    if (Object.values(mockUsers).some(u => u.email === email)) {
      return res(
        ctx.status(400),
        ctx.json({ message: 'Email already exists' })
      )
    }

    // Create mock user
    const userId = `user_${Date.now()}`
    const user: User = { id: userId, name, email, role, avatar: null }
    mockUsers[userId] = user

    return res(
      ctx.status(200),
      ctx.json({
        success: true,
        userId
      })
    )
  }),

  rest.post('/api/auth/verify-otp', async (req, res, ctx) => {
    const { userId, otp } = await req.json()

    // Mock validation
    if (!userId || !otp) {
      return res(
        ctx.status(400),
        ctx.json({ message: 'User ID and OTP are required' })
      )
    }

    // Mock user lookup
    const user = mockUsers[userId]
    if (!user) {
      return res(
        ctx.status(404),
        ctx.json({ message: 'User not found' })
      )
    }

    // Mock OTP validation - accept any 6 digit code
    if (!/^\d{6}$/.test(otp)) {
      return res(
        ctx.status(400),
        ctx.json({ message: 'Invalid OTP' })
      )
    }

    // Generate mock token
    const token = `mock_token_${Date.now()}`
    mockTokens[userId] = token

    return res(
      ctx.status(200),
      ctx.json({
        user,
        token
      })
    )
  })
]

// Create worker
const worker = setupWorker(...handlers)

export const startMockServer = () => {
  worker.start()
}