// Auto-generated by Cursor – Lawsuit Frontend
// Developer note: Do not edit this file directly unless necessary.

import type { Lawyer } from '@/types'

export const mockLawyers: Lawyer[] = [
  {
    id: 'lawyer_001',
    name: 'Adv. Priya Sharma',
    specialization: ['Family Law', 'Consumer Rights'],
    experienceYears: 8,
    rating: 4.6,
    fee: 499,
    location: 'Kolkata, West Bengal',
    languages: ['English', 'Hindi', 'Bengali'],
    avatar: 'https://randomuser.me/api/portraits/women/1.jpg'
  },
  {
    id: 'lawyer_002',
    name: 'Adv. Rohit Sen',
    specialization: ['Criminal Law', 'Corporate Law'],
    experienceYears: 12,
    rating: 4.8,
    fee: 899,
    location: 'Kolkata, West Bengal',
    languages: ['English', 'Hindi'],
    avatar: 'https://randomuser.me/api/portraits/men/2.jpg'
  },
  {
    id: 'lawyer_003',
    name: 'Adv. Amrita Roy',
    specialization: ['Property Law', 'Civil Litigation'],
    experienceYears: 15,
    rating: 4.9,
    fee: 1299,
    location: 'Kolkata, West Bengal',
    languages: ['English', 'Hindi', 'Bengali'],
    avatar: 'https://randomuser.me/api/portraits/women/3.jpg'
  },
  {
    id: 'lawyer_004',
    name: 'Adv. Rajesh Kumar',
    specialization: ['Corporate Law', 'Tax Law'],
    experienceYears: 20,
    rating: 4.7,
    fee: 1499,
    location: 'Delhi, NCR',
    languages: ['English', 'Hindi'],
    avatar: 'https://randomuser.me/api/portraits/men/4.jpg'
  },
  {
    id: 'lawyer_005',
    name: 'Adv. Meera Patel',
    specialization: ['Family Law', 'Women Rights'],
    experienceYears: 6,
    rating: 4.5,
    fee: 399,
    location: 'Mumbai, Maharashtra',
    languages: ['English', 'Hindi', 'Marathi'],
    avatar: 'https://randomuser.me/api/portraits/women/5.jpg'
  }
]

export const specializations = [
  'Family Law',
  'Criminal Law',
  'Corporate Law',
  'Property Law',
  'Civil Litigation',
  'Tax Law',
  'Consumer Rights',
  'Women Rights'
]

export const locations = [
  'Kolkata, West Bengal',
  'Delhi, NCR',
  'Mumbai, Maharashtra'
]

export const languages = [
  'English',
  'Hindi',
  'Bengali',
  'Marathi'
]